version: "3"

services:
  admin_users:
    build: ./build/admin_users
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../admin_users/:/usr/app/
    ports:
      - "8000:8000"
