version: "3"

services:
  admin_users:
    build: ./build/admin_users
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ../admin_users/:/usr/app/
    ports:
      - "8000:8000"

  users_view:
    build: ./build/users_view
    command: nodemon app.js
    volumes:
      - ../users-view/:/app/
    ports:
      - "3000:3000"